version: "2.29.2"

services:

  mariadb:
    container_name: mariadb
    env_file:
      - .env
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_user_password
    restart: unless-stopped
    expose:
      - 3306

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    environment:
      - WORDPRESS_ADMIN_PASSWORD_FILE=/run/secrets/wordpress_admin_password
      - WORDPRESS_USER_PASSWORD_FILE=/run/secrets/wordpress_user_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    secrets:
      - mysql_user_password
      - mysql_root_password
      - wordpress_admin_password
      - wordpress_user_password
    depends_on:
      - mariadb
    restart: always
    expose:
      - 9000

  nginx:
    container_name: nginx
    env_file:
      - .env
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    secrets:
      - ssl_certificate
      - ssl_certificate_key
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wordpress
      o: bind

secrets:
  ssl_certificate:
    file: ../secrets/ssl/nginx-selfsigned.crt
  ssl_certificate_key:
    file: ../secrets/ssl/nginx-selfsigned.key
  mysql_root_password:
    file: ../secrets/mysql-root-password.txt
  mysql_user_password:
    file: ../secrets/mysql-user-password.txt
  wordpress_admin_password:
    file: ../secrets/wordpress-admin-password.txt
  wordpress_user_password:
    file: ../secrets/wordpress-user-password.txt
